### ISSUE TITLE
Allow pre-resolved coordinates in the optimization router extensions

### ISSUE THREAD

**Issue by msioen** [itinero/optimization#28]
Currently the router extensions in the optimization module only allow passing in a set of locations which are then resolved with a MassResolvingAlogrithm.

In our case we want to have more finely-grained control about the resolving before starting calculations. We also cache coordinates/routerpoints for improved performance as long as the router works on the same map.

The 'simplest' way I currently see this is as follows:
- added routerextension methods with routerpoints instead of coordinates (or both coordinates and routerpoints)
- use a 'pre-resolved' massresolver which just returns the preset coordinates/routerpoints
- append the model with routerpoints
- in MappedModel.BuildAbstract, use the new massresolver if the model has known routerpoints, otherwise keep as-is

This solution allows for this change to be limited to the optimization module and is quite small in scope to implement.

Alternatively this could be implemented further downstream as well by giving the WeightmatrixAlgorithm and DirectedWeightMatrixAlgorithm overrides which take routerpoints. There wouldn't be a custom massresolver then but the new overrides of the algorithms would just handle the passed routerpoints. This requires a change in both routing and optimization.

I'm happy to take this up myself. What do you think of the above approach(es)?

**Comment by xivk** [comment]
When thinking about this before I had several similar ideas:

- cache routerpoints per profile at massresolver level, but this may not allow the fine grained controle over the process.
- pass in a custom implementation of the massresolver interface

But it's probably easier to just pass in the routerpoints instead of he lat/lons and be done with it... feel free to build a prototype of what you think it should be but it needs a bit more thinking. I'm on a few days of holiday right now, back on friday, then I can help out...

**Comment by msioen** [comment]
Enjoy your holiday! :)

When you're back I've got some initial pull requests you can have a look at. I opted to add routerpoints to the extensions currently as this aligns best with how the extensions work in the routing module.

routing pr: https://github.com/itinero/routing/pull/205
optimization pr: https://github.com/itinero/optimization/pull/29
